# Generated by Django 5.1.7 on 2025-03-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tempo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaDeEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('estudos', models.ManyToManyField(related_name='dias_de_estudo', to='calendary.estudo')),
            ],
        ),
    ]
